version: '3.8'

services:
  database:
    image: mysql:latest
    env_file: ./.env
    container_name: beachtennisstudentsmanagermysql
    restart: always
    ports:
      - "${DATABASE_PORT:-3307}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
